const mongoose = require('mongoose');

const purchaseSchema = mongoose.Schema(
  {
    supplier: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Supplier',
      required: true,
    },
    items: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Product',
          required: true,
        },
        quantity: {
          type: Number,
          required: true,
        },
        costPrice: {
          type: Number,
          required: true,
        },
      },
    ],
    totalAmount: {
      type: Number,
      required: true,
    },
    status: {
      type: String,
      enum: ['Ordered', 'Received', 'Cancelled'],
      default: 'Ordered',
    },
    receivedAt: {
      type: Date,
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);


const Purchase = mongoose.model('Purchase', purchaseSchema);

module.exports = Purchase;
